name: v2 - Scraping "Liturgi" Data
env:
  GDRIVE_API_KEY: ${{ secrets.GDRIVE_V3_APIKEY }}
run-name: ${{ github.actor }} is updating the liturgy data 🚀
on:
  # Manual trigger.
  workflow_dispatch:
  schedule:
    # * is a special character in YAML so you have to quote this string
    # SOURCE: https://cron.help
    - cron: '0 5,8,11,14,17,20 * * 6'
    - cron: '0 12 * * *'
jobs:
  Run-Python:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Preamble logging
        run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      
      # If you don't check out files, you will fail at accessing/writing files on repo!
      # SOURCE: https://stackoverflow.com/a/65027251
      - name: Necessary checking out
        uses: actions/checkout@v3

      - name: Setup the Python runner
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
        
      # SOURCE: https://github.com/marketplace/actions/python-dependency-installation
      - name: Install dependencies
        uses: py-actions/py-dependency-install@v4
        with:
          path: "requirements.txt"
          update-pip: "false"
          update-setuptools: "false"
          update-wheel: "false"
      
      # SOURCE: https://www.geeksforgeeks.org/run-python-script-in-github-actions/
      - name: Running the updater
        run: python v2/scripts/scraper_pdf_liturgi.py
      
      # SOURCE: https://github.com/marketplace/actions/add-commit-and-push
      - name: Commiting changes to files
        uses: actions4git/setup-git@v1
      - run: git add v2/*
      - run: git commit --message "(v2) Scraped the Liturgi content"
      - run: git push origin main --force
        
      - run: echo "🍏 This job's status is ${{ job.status }}."
